# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 550a0deaf693db05516adf5f8e11a9c607a14a365fbcc6ad7e1d4f42a07472e2d61d619504e0e929afc6ec6450165138ef316f5e729ddc1229eacdec16e7f132

test:
  secret_key_base: 5da44b6c2aff59d1dde2676a280b5be8437d4cbd9890e246030baaf27ab46a77404a3fdf7e613b425b000cda2eec01dc3339d6091a3b95070542c7d3ba17c052

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
